In [5]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense, Flatten, BatchNormalization, Conv2D, MaxPool2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import confusion_matrix
import itertools
import os
import shutil
import random
import glob
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
%matplotlib inline

In [ ]:
os.chdir('D:/Acads/Coding/Machine Learning/Keras/dogs-vs-cats')
if os.path.isdir('train/dog') is False:
    os.makedirs('train/dog')
    os.makedirs('train/cat')
    os.makedirs('valid/dog')
    os.makedirs('valid/cat')
    os.makedirs('test/dog')
    os.makedirs('test/cat')
    
    for c in random.sample(glob.glob('train/cat*'), 500):
        shutil.move(c, 'train/cat' )
    for c in random.sample(glob.glob('train/dog*'), 500):
        shutil.move(c, 'train/dog')
    for c in random.sample(glob.glob('train/cat*'), 100):
        shutil.move(c, 'valid/cat')
    for c in random.sample(glob.glob('train/dog*'), 100):
        shutil.move(c, 'valid/dog')
    for c in random.sample(glob.glob('train/cat*'), 50):
        shutil.move(c, 'test/cat')
    for c in random.sample(glob.glob('train/dog*'), 50):
        shutil.move(c, 'test/dog')

In [2]:
train_path = 'D:/Acads/Coding/Machine Learning/Keras/dogs-vs-cats/train'
valid_path = 'D:/Acads/Coding/Machine Learning/Keras/dogs-vs-cats/valid'
test_path = 'D:/Acads/Coding/Machine Learning/Keras/dogs-vs-cats/test'

In [ ]:
train_batches = ImageDataGenerator(preprocessing_function=tf.keras.applications.vgg16.preprocess_input) \
    .flow_from_directory(directory=train_path, target_size=(224,224), classes=['cat', 'dog'], batch_size=10)
valid_batches = ImageDataGenerator(preprocessing_function=tf.keras.applications.vgg16.preprocess_input) \
    .flow_from_directory(directory=valid_path, target_size=(224,224), classes=['cat', 'dog'], batch_size=10)
test_batches = ImageDataGenerator(preprocessing_function=tf.keras.applications.vgg16.preprocess_input) \
    .flow_from_directory(directory=test_path, target_size=(224,224), classes=['cat', 'dog'], batch_size=10, shuffle=False)

In [ ]:
model = Sequential([
    Conv2D(filters=32, kernel_size=(3, 3), activation='relu', padding='same', input_shape=(224,224, 3)),
    MaxPool2D(pool_size=(2,2), strides=2),
    Conv2D(filters=64, kernel_size=(3, 3), activation='relu', padding='same'),
    MaxPool2D(pool_size=(2,2), strides=2),
    Flatten(),
    Dense(units=2, activation='softmax')
])

In [32]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 224, 224, 32)      896       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 112, 112, 32)      0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 112, 112, 64)      18496     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 56, 56, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 200704)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 401410    
Total params: 420,802
Trainable params: 420,802
Non-trainable params: 0
________________________________________________

In [ ]:
model.compile(optimizer=Adam(learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

In [37]:
model.fit(x=train_batches, validation_data=valid_batches, epochs=10, verbose=2)

Epoch 1/10
100/100 - 44s - loss: 4.8253e-04 - accuracy: 1.0000 - val_loss: 3.2677 - val_accuracy: 0.5800
Epoch 2/10
100/100 - 50s - loss: 4.3380e-04 - accuracy: 1.0000 - val_loss: 3.2634 - val_accuracy: 0.5800
Epoch 3/10
100/100 - 47s - loss: 3.9281e-04 - accuracy: 1.0000 - val_loss: 3.2701 - val_accuracy: 0.5800
Epoch 4/10
100/100 - 48s - loss: 3.5623e-04 - accuracy: 1.0000 - val_loss: 3.2640 - val_accuracy: 0.5800
Epoch 5/10
100/100 - 48s - loss: 3.2594e-04 - accuracy: 1.0000 - val_loss: 3.2663 - val_accuracy: 0.5800
Epoch 6/10
100/100 - 49s - loss: 2.9940e-04 - accuracy: 1.0000 - val_loss: 3.2757 - val_accuracy: 0.5900
Epoch 7/10
100/100 - 46s - loss: 2.7743e-04 - accuracy: 1.0000 - val_loss: 3.2770 - val_accuracy: 0.5850
Epoch 8/10
100/100 - 47s - loss: 2.5545e-04 - accuracy: 1.0000 - val_loss: 3.2703 - val_accuracy: 0.5850
Epoch 9/10
100/100 - 45s - loss: 2.3799e-04 - accuracy: 1.0000 - val_loss: 3.2716 - val_accuracy: 0.5850
Epoch 10/10
100/100 - 45s - loss: 2.2064e-04 - accuracy

In [42]:
predictions = model.predict(x=test_batches, verbose=0)

In [43]:
np.round(predictions)

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.

In [6]:
vgg16_model = tf.keras.applications.vgg16.VGG16()

In [9]:
vgg16_model.summary()

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [7]:
model = Sequential()
type(model)

tensorflow.python.keras.engine.sequential.Sequential

In [8]:
for layer in vgg16_model.layers[:-1]:
    model.add(layer)
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       2

In [9]:
for layer in model.layers:
    layer.trainable = False

In [10]:
model.add(Dense(units=2, activation='softmax'))

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       2

In [11]:
model.compile(optimizer=Adam(learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

In [12]:
import os.path
if os.path.isfile('models/VGG16_2_trial_model.h5') is False:
    model.save('models/VGG16_2_trial_model.h5')

In [12]:
model.fit(x=train_batches, validation_data=valid_batches, epochs=5, verbose=2)

Epoch 1/5
100/100 - 401s - loss: 0.0282 - accuracy: 0.9950 - val_loss: 0.0436 - val_accuracy: 0.9900
Epoch 2/5
100/100 - 324s - loss: 0.0219 - accuracy: 0.9960 - val_loss: 0.0453 - val_accuracy: 0.9900
Epoch 3/5
100/100 - 327s - loss: 0.0170 - accuracy: 0.9970 - val_loss: 0.0427 - val_accuracy: 0.9850
Epoch 4/5
100/100 - 327s - loss: 0.0136 - accuracy: 0.9980 - val_loss: 0.0443 - val_accuracy: 0.9900
Epoch 5/5
100/100 - 302s - loss: 0.0117 - accuracy: 0.9990 - val_loss: 0.0427 - val_accuracy: 0.9850
10/10 - 28s


array([[9.99976754e-01, 2.33032843e-05],
       [9.99978781e-01, 2.12582709e-05],
       [9.99965668e-01, 3.43416432e-05],
       [9.99915242e-01, 8.47804768e-05],
       [9.99999285e-01, 6.80462222e-07],
       [9.99865651e-01, 1.34348506e-04],
       [9.98876154e-01, 1.12378597e-03],
       [9.99970317e-01, 2.96478811e-05],
       [9.99993563e-01, 6.40288499e-06],
       [1.00000000e+00, 1.19763079e-08],
       [9.99677896e-01, 3.22060427e-04],
       [9.99997258e-01, 2.71614135e-06],
       [2.76572436e-01, 7.23427594e-01],
       [9.99993682e-01, 6.25906205e-06],
       [9.99699831e-01, 3.00240004e-04],
       [9.95567501e-01, 4.43247752e-03],
       [9.99339402e-01, 6.60623133e-04],
       [9.99978423e-01, 2.16156150e-05],
       [9.99132931e-01, 8.67051014e-04],
       [9.99998093e-01, 1.89850789e-06],
       [9.99527097e-01, 4.72951826e-04],
       [9.99996066e-01, 3.91947560e-06],
       [9.94594634e-01, 5.40533569e-03],
       [9.99996662e-01, 3.39629491e-06],
       [9.994754

In [1]:
import os.path
if os.path.isfile('models/VGG16_2_trial_model.h5') is False:
    model.save('models/VGG16_2_trial_model.h5')

NameError: name 'model' is not defined

In [13]:
predictions = model.predict(x=test_batches, verbose = 2)

10/10 - 19s


In [15]:
test_batches.classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
#Accuracy on test set
correct = 0
for i in range(50):
    #print(predictions[i][0], test_batches.classes[i])
    if predictions[i][0] >= 0.5 and test_batches.classes[i] == 0:
        correct+=1
    elif predictions[i][1] >= 0.5 and test_batches.classes[i] == 1:
        correct+=1
print(correct*100/50, "%")    

98.0 %
