In [1]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

#sample creation

train_labels = []
train_samples = []

for i in range(50):
    random_younger = randint(13, 64)
    train_samples.append(random_younger)
    train_labels.append(1)

    random_older = randint(65, 100)
    train_samples.append(random_older)
    train_labels.append(0)

for i in range(1000):
    random_younger = randint(13, 64)
    train_samples.append(random_younger)
    train_labels.append(0)

    random_older = randint(65, 100)
    train_samples.append(random_older)
    train_labels.append(1)

train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels, train_samples = shuffle(train_labels, train_samples)

scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1, 1))

print(scaled_train_samples)

###

[[0.10344828]
 [0.64367816]
 [0.04597701]
 ...
 [0.52873563]
 [0.31034483]
 [0.11494253]]


In [7]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

#Building the model
model = Sequential([
    Dense(units = 16, input_shape = (1,), activation = 'relu'),
    Dense(units= 32, activation = 'relu'), #relu = max(0, a). Alternatives are sigmoid and softmax functions!
    Dense(units = 2, activation = 'softmax') #final output layer giving probabilities of the output
])

model.compile(optimizer=Adam(learning_rate=0.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
#model.fit(x=scaled_train_samples, y=train_labels, batch_size=10, epochs=30, shuffle=True, verbose=2) #verbose tells level of output
model.fit(x=scaled_train_samples, y=train_labels, validation_split=0.1, batch_size=10, epochs=30, shuffle=True, verbose=2) #with a vaildation set


Epoch 1/30
189/189 - 1s - loss: 0.6375 - accuracy: 0.5545 - val_loss: 0.6279 - val_accuracy: 0.6000
Epoch 2/30
189/189 - 0s - loss: 0.6132 - accuracy: 0.6460 - val_loss: 0.5951 - val_accuracy: 0.7143
Epoch 3/30
189/189 - 0s - loss: 0.5782 - accuracy: 0.7201 - val_loss: 0.5596 - val_accuracy: 0.7667
Epoch 4/30
189/189 - 0s - loss: 0.5433 - accuracy: 0.7683 - val_loss: 0.5233 - val_accuracy: 0.8143
Epoch 5/30
189/189 - 0s - loss: 0.5070 - accuracy: 0.8085 - val_loss: 0.4837 - val_accuracy: 0.8381
Epoch 6/30
189/189 - 0s - loss: 0.4684 - accuracy: 0.8503 - val_loss: 0.4489 - val_accuracy: 0.8667
Epoch 7/30
189/189 - 0s - loss: 0.4362 - accuracy: 0.8656 - val_loss: 0.4192 - val_accuracy: 0.8667
Epoch 8/30
189/189 - 0s - loss: 0.4074 - accuracy: 0.8799 - val_loss: 0.3931 - val_accuracy: 0.8905
Epoch 9/30
189/189 - 0s - loss: 0.3823 - accuracy: 0.8884 - val_loss: 0.3715 - val_accuracy: 0.9000
Epoch 10/30
189/189 - 0s - loss: 0.3602 - accuracy: 0.9005 - val_loss: 0.3539 - val_accuracy: 0.9095

In [9]:
#making test set

test_labels = []
test_samples = []

for i in range(10):
    random_younger = randint(13, 64)
    test_samples.append(random_younger)
    test_labels.append(1)

    random_older = randint(65, 100)
    test_samples.append(random_older)
    test_labels.append(0)

for i in range(200):
    random_younger = randint(13, 64)
    test_samples.append(random_younger)
    test_labels.append(0)

    random_older = randint(65, 100)
    test_samples.append(random_older)
    test_labels.append(1)

test_labels = np.array(test_labels)
test_samples = np.array(test_samples)
test_labels, test_samples = shuffle(test_labels, test_samples)

scaled_test_samples = scaler.fit_transform(test_samples.reshape(-1, 1))
###

In [12]:
predictions = model.predict(x=scaled_test_samples, batch_size=10, verbose=0)
print(predictions)

[[0.9793452  0.02065476]
 [0.9786078  0.02139219]
 [0.07299537 0.9270047 ]
 [0.97621834 0.02378169]
 [0.9787754  0.02122467]
 [0.9324081  0.06759194]
 [0.49057642 0.50942355]
 [0.97783864 0.02216138]
 [0.0528025  0.94719744]
 [0.33827186 0.6617281 ]
 [0.978231   0.021769  ]
 [0.03115033 0.9688496 ]
 [0.77362835 0.22637159]
 [0.02230924 0.97769076]
 [0.07809337 0.9219066 ]
 [0.9791709  0.02082916]
 [0.9791709  0.02082916]
 [0.9401724  0.05982767]
 [0.8983361  0.10166382]
 [0.21344028 0.7865597 ]
 [0.03556701 0.96443295]
 [0.9779537  0.02204627]
 [0.01950561 0.9804944 ]
 [0.03556701 0.96443295]
 [0.9623559  0.03764416]
 [0.95266944 0.04733051]
 [0.01950561 0.9804944 ]
 [0.92264813 0.07735185]
 [0.9786405  0.02135949]
 [0.04334794 0.95665205]
 [0.02550539 0.9744946 ]
 [0.97411966 0.02588041]
 [0.02086139 0.9791387 ]
 [0.03115033 0.9688496 ]
 [0.97704244 0.02295759]
 [0.12590982 0.8740902 ]
 [0.06845681 0.9315432 ]
 [0.9401724  0.05982767]
 [0.8983361  0.10166382]
 [0.97704244 0.02295759]


In [21]:
rounded_predictions = np.argmax(predictions, axis = -1)
print(rounded_predictions)

[0 0 1 0 0 0 1 0 1 1 0 1 0 1 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0 1 1 0 1 1 0 1 1
 0 0 0 1 1 0 1 0 1 1 0 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1 1 0 0 1 0 0 0 1 1 1 0
 0 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1
 0 1 0 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0 1 0 1 1 1 1 0 1 1 0 0 0 0 1 1 0 1 1 0
 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 1 1 1 0 0 0 0 1 0 1
 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 1 1 0 0 1 0 1 0 0
 0 0 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1 1 1 1 1 1 0 1 1 0 1
 0 0 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 1 1 1 1 0 1 0
 1 0 1 0 0 0 1 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 1 1 1 1 1 0 0 0 1 0 0 1 0
 0 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 0
 0 1 0 1 0 0 0 1 0 1 0 0 1 1 0 0 1 1 0 1 0 0 1 0 0 1 1 1 1 1 1 0 1 0 0 0 0
 0 0 0 1 0 1 0 1 1 0 1 0 1]


In [24]:
import os.path
if os.path.isfile('models/medical_trial_model.h5') is False:
    model.save('models/medical_trial_model.h5')

In [25]:
from tensorflow.keras.models import load_model
new_model = load_model('models/medical_trial_model.h5')

In [26]:
new_model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 16)                32        
_________________________________________________________________
dense_13 (Dense)             (None, 32)                544       
_________________________________________________________________
dense_14 (Dense)             (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [29]:
new_model.predict(x=scaled_test_samples, batch_size = 10, verbose=0)

array([[0.9793452 , 0.02065476],
       [0.9786078 , 0.02139219],
       [0.07299537, 0.9270047 ],
       [0.97621834, 0.02378169],
       [0.9787754 , 0.02122467],
       [0.9324081 , 0.06759194],
       [0.49057642, 0.50942355],
       [0.97783864, 0.02216138],
       [0.0528025 , 0.94719744],
       [0.33827186, 0.6617281 ],
       [0.978231  , 0.021769  ],
       [0.03115033, 0.9688496 ],
       [0.77362835, 0.22637159],
       [0.02230924, 0.97769076],
       [0.07809337, 0.9219066 ],
       [0.9791709 , 0.02082916],
       [0.9791709 , 0.02082916],
       [0.9401724 , 0.05982767],
       [0.8983361 , 0.10166382],
       [0.21344028, 0.7865597 ],
       [0.03556701, 0.96443295],
       [0.9779537 , 0.02204627],
       [0.01950561, 0.9804944 ],
       [0.03556701, 0.96443295],
       [0.9623559 , 0.03764416],
       [0.95266944, 0.04733051],
       [0.01950561, 0.9804944 ],
       [0.92264813, 0.07735185],
       [0.9786405 , 0.02135949],
       [0.04334794, 0.95665205],
       [0.

In [31]:
json_string = model.to_json()

In [33]:
json_string

'{"class_name": "Sequential", "config": {"name": "sequential_4", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 1], "dtype": "float32", "sparse": false, "ragged": false, "name": "dense_12_input"}}, {"class_name": "Dense", "config": {"name": "dense_12", "trainable": true, "batch_input_shape": [null, 1], "dtype": "float32", "units": 16, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_13", "trainable": true, "dtype": "float32", "units": 32, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null

In [34]:
# can get model back from json string using model_from_json

In [36]:
# if you only have the weights saved then define another model let us suppose model2 with same architecture and load_weights
# using the file loaction into the model2.